name: Get Indexes

on:
  workflow_dispatch:
  schedule:
    # time in UTC
    - cron: '38 5,11,17 * * *'

jobs:
  download-indexes:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: runner
        run: bash getindex.sh

      - name: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index files
